# Generated by Django 5.0.6 on 2024-06-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_name_alter_amenity_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(default='Seoul', max_length=80),
        ),
    ]
