# Generated by Django 5.0.6 on 2024-06-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_pets_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=True, help_text='Does this house allow pets?', verbose_name='Pets Allowed?'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(help_text='Positive Numbers Only'),
        ),
    ]
